# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'depth_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Depth(object):
    # def __init__(self, parent=None):
    #     super(Ui_Depth, self).__init__(parent)
    
    def setupUi(self, Form, value):
        Form.setObjectName("depth")
        Form.resize(800, 800)
        Form.setContextMenuPolicy(QtCore.Qt.NoContextMenu)

        # Boat picture
        self.depth_boat = QtWidgets.QLabel(Form)
        self.depth_boat.setGeometry(QtCore.QRect(70, 110, 641, 531))
        self.depth_boat.setText("")
        self.depth_boat.setPixmap(QtGui.QPixmap("depth.png"))
        self.depth_boat.setObjectName("depth_boat")
        
        # Depth value
        self.depth_nb = QtWidgets.QLCDNumber(Form)
        self.depth_nb.setGeometry(QtCore.QRect(390, 420, 101, 51))
        self.depth_nb.setFrameShape(QtWidgets.QFrame.Box)
        self.depth_nb.setFrameShadow(QtWidgets.QFrame.Plain)
        self.depth_nb.setLineWidth(4)
        self.depth_nb.setMidLineWidth(0)
        self.depth_nb.setProperty("value", value)
        self.depth_nb.setObjectName("depth_nb")

        # Unit text display
        self.m = QtWidgets.QLabel(Form)
        self.m.setGeometry(QtCore.QRect(495, 428, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(18)
        self.m.setFont(font)
        self.m.setObjectName("m")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, depth):
        _translate = QtCore.QCoreApplication.translate
        depth.setWindowTitle(_translate("Depth", "Depth"))
        self.m.setText(_translate("Form", "m"))


    def update(self, depth_value):
        self.depth_nb.display(depth_value)
        self.depth_boat.setPixmap(QtGui.QPixmap("depth.png"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QWidget()
    ui = Ui_Depth()
    ui.setupUi(window, 0.)
    window.show()
    sys.exit(app.exec_())
