# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VMG.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VMG(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(210, 400, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")


        self.vmg_nb = QtWidgets.QLCDNumber(Form)
        self.vmg_nb.setGeometry(QtCore.QRect(330, 440, 64, 23))
        self.vmg_nb.setObjectName("lcdNumber")
        self.vmg_nb.setProperty("intValue", 12)

        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(410, 400, 251, 101))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(24)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")


        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, -10, 671, 591))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("VMG.png"))
        self.label.setObjectName("label")


        self.wind_angle_nb = QtWidgets.QLCDNumber(Form)
        self.wind_angle_nb.setGeometry(QtCore.QRect(330, 220, 64, 23))
        self.wind_angle_nb.setObjectName("lcdNumber_2")
        self.wind_angle_nb.setProperty("intValue", 45)


        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(400, 190, 41, 81))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(24)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")


        self.label.raise_()
        self.label_2.raise_()
        self.vmg_nb.raise_()
        self.label_3.raise_()
        self.wind_angle_nb.raise_()
        self.label_4.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "VMG"))
        self.label_3.setText(_translate("Form", "knots"))
        self.label_4.setText(_translate("Form", "°"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_VMG()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
