# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gite_tangage_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_gite_tangage(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 800)
        #Valeurs à modifier
        self.gite_value = 54
        self.tangage_value = 54


        self.image_gite = QtWidgets.QLabel(Form)
        self.image_gite.setGeometry(QtCore.QRect(0, 0, 641, 531))
        self.image_gite.setText("")
        self.image_gite.setPixmap(QtGui.QPixmap("gite.png"))
        self.image_gite.setObjectName("gite_image")

        self.tangage = QtWidgets.QLabel(Form)
        self.tangage.setGeometry(QtCore.QRect(102, 330, 611, 581))
        self.tangage.setText("")
        self.tangage.setPixmap(QtGui.QPixmap("../tangage.png"))
        self.tangage.setObjectName("tangage")

        self.image_tangage = QtWidgets.QLabel(Form)
        self.image_tangage.setGeometry(QtCore.QRect(150, 350, 641, 531))
        self.image_tangage.setText("")
        self.image_tangage.setPixmap(QtGui.QPixmap("tangage.png"))
        self.image_tangage.setObjectName("tangage_image")

        self.label_gite = QtWidgets.QLabel(Form)
        self.label_gite.setGeometry(QtCore.QRect(20, 70, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(18)
        self.label_gite.setFont(font)
        self.label_gite.setObjectName("GiteAngle")

        self.label_tangage = QtWidgets.QLabel(Form)
        self.label_tangage.setGeometry(QtCore.QRect(20, 440, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(18)
        self.label_tangage.setFont(font)
        self.label_tangage.setObjectName("GiteTangage")

        self.gite_nb = QtWidgets.QLCDNumber(Form)
        self.gite_nb.setGeometry(QtCore.QRect(180, 70, 101, 51))
        self.gite_nb.setFrameShadow(QtWidgets.QFrame.Plain)
        self.gite_nb.setLineWidth(2)
        self.gite_nb.setMidLineWidth(0)
        self.gite_nb.setProperty("intValue", self.gite_value)
        self.gite_nb.setObjectName("gite_nb")

        self.tangage_nb = QtWidgets.QLCDNumber(Form)
        self.tangage_nb.setGeometry(QtCore.QRect(232, 440, 101, 51))
        self.tangage_nb.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tangage_nb.setLineWidth(2)
        self.tangage_nb.setMidLineWidth(0)
        self.tangage_nb.setProperty("intValue", self.tangage_value)
        self.tangage_nb.setObjectName("tangage_nb")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_gite.setText(_translate("Form", "Gite angle:"))
        self.label_tangage.setText(_translate("Form", "Tangage angle:"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_gite_tangage()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
